version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ./.test/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: 9c-rudolf-test
