name: Build & Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install
        shell: bash
        run: yarn install --immutable

      - name: Init test database
        run: docker compose up -d

      - name: Give permissions to test database
        run: chown -R node:node .test/

      - name: Test
        run: yarn test:e2e

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
